### ISSUE TITLE
How best to interface with json modules

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#134]
@vortexing asks about how to use our repository for her own (ambiguously benevolent, I presume) purposes.

Basically it comes down to if our stuff will ever be useful for their stuff - if yes, then fork/clone. If no, then steal our formatting and structure ([import repo](https://github.com/new/import)) and burn it all down to start fresh.

**Comment by sgosline** [comment]
Conclusion: reformat JSON files into a single one with a 'tag' tuple with a shiny interface on top to allow people to select terms that include a subset of annotations, e.g. NF, ngs, common.

**Comment by vortexing** [comment]
Not fully addressed is the submission of terms, tags, key-value pairs that we (Fred Hutch) curate, that are not in the current meta-dictionary you have, back to a location where you (Sage) can then refer to in order to incorporate them should they be mutually useful.  Perhaps this is simply via github for now, but perhaps there is a better way to do this long term?

**Comment by teslajoy** [comment]
@vortexing would the https://shiny.synapse.org/users/nsanati/annotationUI/
upload your modules functionality solve this issue?

**Comment by kdaily** [comment]
Partially solved by annotationUI, but we will not take externally defined terms back into the repo for now, unless it goes through the weekly meeting.
