### ISSUE TITLE
Establish release process and release numbering scheme

### ISSUE THREAD

**Issue by teslajoy** [Sage-Bionetworks/synapseAnnotations#144]
There are 2 required and 1 optional places that release needs to exist: 
1. Annotation UI **title** 
2. Each file's **annotation dictionary** 
3. OPTIONAL: **project's wiki** or ideally a file-view schema itself

Scheme:  **v1.0.0**
Incrementing should be done via _major_ and _minor_ changes 

**major changes** would increment the version number **v1** by: 
- data structure changes (ex. yaml to json or json to mongodb)

**minor changes** by:  
- addition of a new project **.0.**
- addition or manipulation of keys **.0**

changes in values would not significantly effect the _structure of schemas in synapse_, thus are not versioned.

Helpful links:  
https://help.github.com/articles/creating-releases/
https://github.com/alexdobin/STAR/releases

**Comment by kdaily** [comment]
I might say that certain changes to keys and/or values would warrant a new version - renaming a key, or changing the meaning of a value, to name two.

**Comment by teslajoy** [comment]
key and value changes occur frequently and consequently increment to larger numbers. 

The reason behind the proposed scheme was to have the tail digit **.0** grow longer (faster) while keeping the major changes in mind.

**Comment by kdaily** [comment]
I agree with almost all of that statement, with a caveat that I was trying to say above.

The de facto standard for releasing (software) is [Semantic Versioning](http://semver.org/) - essentially what STAR is using. The standard states that you change the "MAJOR version when you make incompatible API changes".

I think there are some (but definitely not most) key/value changes that would be similar to 'incompatible API changes'. Adding a new key or a new value that have no conflict would be a minor change (if in the minified) or a patch (if in a consortium-specific). Changing an existing value to some other value, for example because of an error or change in definition, could be considered a breaking change. Changing a key is definitely a breaking change (you can no longer run a successful query by including that key using any of the clients - they will return an error).

**Comment by teslajoy** [comment]
After meeting release versioning consensus: 

Major version would increment the version number **v1** by:
changes in data structure (ex. yaml to json or json to mongodb)
changes in keys 
changes in values 

Minor version **.0.** would increment by 
adding keys
adding values 

PATCH version **.0**
errors that don't break the api 

The release will be placed on the project wikis and annotation UI shiny app title (possibly embedded in url).
