### ISSUE TITLE
In experimentalData.json, link for "pancreas cancer" says "pancreatic cancer"

### ISSUE THREAD

**Issue by meredithslota** [Sage-Bionetworks/synapseAnnotations#213]
https://www.ebi.ac.uk/ols/ontologies/doid/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FDOID_1793 links to the term "pancreatic cancer" but our value in experimentalData.json says "Pancreas Cancer". Which is correct in this case and should we be trying to stay close to what the source says?

**Comment by allaway** [comment]
A GI oncologist I used to work with would always call it "pancreas cancer," but I think "pancreatic cancer" is still the preferred term.  "pancreas cancer" is also not listed as a synonym in the link so I think "pancreatic cancer" is probably better. 

This also makes me wonder whether we should be using the official oncotree names and codes since that seems to be a standard these days? http://oncotree.mskcc.org/oncotree/#/home

**Comment by kkdang** [comment]
LEA committee decides pancreatic cancer.
