### ISSUE TITLE
document process for release

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#392]
1. tagged the issues/prs with labels (change/modify/remove key, change structure, etc.)
1. merge develop to master
1. Run the ruby script to generate CHANGELOG.md and commit direct to master
1. make a version branch
1. Use the version branch to draft a GH release named v.0.0.0, description v0.0.0, add part of CHANGELOG.md specific to changes in this release to the GH release text

To do: figure out why we need long-running branches instead of using the master branch at a commit as the release.

**Comment by karawoo** [comment]
@kdaily any updates on this? I think we should start prepping the next annotations release soon.

**Comment by kdaily** [comment]
I'll try to address it this week.

**Comment by kdaily** [comment]
need github api token to run this

**Comment by kdaily** [comment]
New process:

1. merge develop into master and push to github
2. run changelog generator and set parameter `--future-release` to the new release number `vX.X.X`.
3. commit new `CHANGELOG.md` directly to master and push to github 
4. create new release on Github using web interface.
5. copy new section of CHANGELOG.md to release notes section.
6. dance

**Comment by karawoo** [comment]
@milen-sage I think you succeeded in updating the Annotation Modules table (syn10242922). Could you add the steps to do that here? Then I will compile everything and add it to our CONTRIBUTING.MD and close this issue.

**Comment by milen-sage** [comment]
1. clone repo 
https://github.com/Sage-Bionetworks/annotator/
2. cd to local repo folder and install the annotator package 
python setup.py install
3. run (command line)
annotator json2table

Notes:

a) The annotator json2table code creates a dataframe (based on which the table syn10242922 is updated) using the synapseAnnotations json files as input (e.g. experimentalData.json, ngs.json, etc.).

The code in annotator doing that

https://github.com/Sage-Bionetworks/annotator/blob/master/annotator/schema.py#L87
through 
https://github.com/Sage-Bionetworks/annotator/blob/master/annotator/schema.py#L103

expects that _input json files use property 'value' in enumValues and not property 'name'_ (.); as in  

https://github.com/Sage-Bionetworks/synapseAnnotations/blob/master/synapseAnnotations/data/ngs.json#L154 

for instance. 

If (.) is not satisfied, the created dataframe contains multiple columns with the same name (i.e. 'name'), which consequently results in an opaque error message when annotator crashes.

To avoid that we might want to enforce/account for (.) in our json files. Only ngs.json violates (.) currently.

b) I assume the annotator script was coded for pandas < 20 and/or python < 3; in later versions of both we no longer need the line 

https://github.com/Sage-Bionetworks/annotator/blob/master/annotator/__main__.py#L110

The line results in unwanted characters, say 'b', pre-pended to a string in a cell of the dataframe, say the description field in syn10242922.

Regarding b): removing the above line is easy, but we might want to test in different environments.
Regarding a): we might want to correct ngs.json for the next synnapseAnnotations release and/or change the annotator script (locally I changed the annotator script).

Otherwise, steps 1-3 work.

**Comment by karawoo** [comment]
Thank you @milen-sage!!

> Regarding a): we might want to correct ngs.json for the next synnapseAnnotations release and/or change the annotator script

It looks like it has already been changed (by you!) on `develop`, so from the next release onward it should be ok.
