### ISSUE TITLE
Data quality flag annotation

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/synapseAnnotations#449]
In AMP-AD (and maybe other consortia?) we sometimes have data shared that later undergoes QC and is flagged as unreliable or low quality. Typically we don't remove this data, but there should be a way to  flag it for future analysts. How do others approach this? What do we think about having a data quality annotation? I can think of a couple options here:
1. We have one annotation, `dataQualityFlag` or similar, that would have values like `suspected problem`, `known problem`, `unchecked`, `suspected good`, and so on. The value of the annotation on a given file could change over time. Probably in reality this annotation would most often be used when data was suspected or known to be faulty.
2. We have separate annotations for different types of quality issues, e.g. `corruptedFile: true`, `contaminatedSample: true` etc. Obviously this could balloon into a huge number of potential data quality issues which might be harder to maintain, but would give more useful information about the nature of the data quality issues. 

If we had support for multiple annotation values, we could combine the approaches above with a single `dataQualityFlags` annotation key that took a list of the different types of quality problems associated with that file.

A few examples from elsewhere:
* [ENCODE](https://www.encodeproject.org/help/getting-started/status-terms/#FileStatuses)
* [NASA](https://wiki.earthdata.nasa.gov/display/NASAISO/Quality+Flags+in+CMR+Metadata)
* [iDigBio](https://github.com/iDigBio/idigbio-search-api/wiki/Data-Quality-Flags)

**Comment by allaway** [comment]
I like the idea in principle, but my only concern is that data quality can be subjective. I would probably lean towards the side of providing less confidence rather than more, as I wouldn't want folks to see `suspected good` and then jump into analysis without any sort of QC - not that that ever happens, right? :) On the other hand, People might assume the data is crap if they don't see `suspected good` or `good` or whatever.

**Comment by allaway** [comment]
The above doesn't apply if there are specific provable reasons the data are poor - i.e. the RNAseq is all mouse reads when it is supposed to be human, etc. 

I do like the combination of the two approaches where you can cite the specific reason a data file might be suspect. As you mention, arrayed annotations required etc....

**Comment by amapeters** [comment]
I agree that flagging something as good may be an issue and subjective, but we need a flag for when a sample is suspected to be contaminated, or where there is evidence that the sample is not from the individual they thought. These are cases where data providers recommend that we remove the sample.

**Comment by amapeters** [comment]
As Kara states, this is an issue where data is released in batches before a final QC can be done

**Comment by amapeters** [comment]
@karawoo - I like the iDigBio flags. Maybe it should be as simple as 'removed', 'remapped', 'replaced'

**Comment by kelshmo** [comment]
I support developing a strategy to annotate data as unreliable - I have seen this take place in CMC; where a sample swap/contamination/low quality was identified at a later date due to more robust QC, labs even checking each other within the consortia. It seems like a good open science practice to communicate all findings. I view the flag as an alert to down stream researchers to understand how the data was QCed as well.
